version: '3.8'

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/contactdb
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"  # Expose to host IP (10.10.1.60)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
